name: Update README with Blog Posts

on:
  schedule:
    - cron: '0 * * * *' # 매 시간마다 실행
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Pull latest blog posts
        run: |
          curl -s https://rss.blog.naver.com/sosow0212.xml | 
          grep -oP '(?<=<title><!\[CDATA\[)[^\]]+' | 
          sed '1d' | head -n 3 > latest-blogs.txt
      - name: Update README
        run: |
          echo "## 📘 Latest Blog Posts" > blog-section.md
          while IFS= read -r line; do
            echo "- [$line](https://blog.naver.com/sosow0212)" >> blog-section.md
          done < latest-blogs.txt
          sed -i '/## 📘 Latest Blog Posts/r blog-section.md' README.md
      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git commit -m "Updated README with latest blog posts"
          git push
